name = "kitsune-worker"
main = "src/index.ts"
compatibility_date = "2025-05-01"

# Binding for the Rate Limiting API.
# This creates a rate limiter named RATE_LIMITER accessible in the Worker.
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"

# This ID must be a unique integer for your account. It partitions this
# limiter from any others you might create.
namespace_id = "1337"

# The actual rate limit: 10 requests per 60 seconds. Adjust as needed.
simple = { limit = 10, period = 60 }

# Environment variables for local development
[vars]
KITSUNE_API_URL = "https://hostedbackend.com/analyze"
ENVIRONMENT = "development" 